hello = [
    "Greetings",
    "Hi",
    "Howdy",
    "Welcome",
    "Bonjour",
    "Buenas noches",
    "Buenos dias",
    "Good day",
    "Good morning",
    "Hey",
    "Hi-ya",
    "How are you",
    "How goes it",
    "Howdy-do",
    "Shalom",
    "what's happening",
    "what's up",
]
